### ISSUE TITLE
Tainted Glass, Beacon and Anvil!

### ISSUE THREAD

**Issue by RedstoneGunMade** [MinePocket/PE-like-PC-Addon#2]
Add Tainted Glass, Beacon and Anvil

**Comment by minecraftmuse3** [comment]
I can make a render for the anvil, if you want :)

**Comment by jv110** [comment]
@minecraftmuse3 No need, we can copy it from PC

**Comment by minecraftmuse3** [comment]
Can you show me how to do that?

**Comment by jv110** [comment]
Well, here's the source code for 1.6.2 https://github.com/byteandahalf/Minecraft

**Comment by minecraftmuse3** [comment]
@jv110 So how do you port it to PE? I took a look and I could find no correlation between PC and PE renders.

**Comment by RedstoneGunMade** [comment]
Because are similar @minecraftmuse3

**Comment by RedstoneGunMade** [comment]
@minecraftmuse3 you want help we?

**Comment by minecraftmuse3** [comment]
@RedstoneGunMade Sorry, I didn't understand that.

**Comment by jv110** [comment]
@minecraftmuse3 Just change the function names. The numbers are the same.

**Comment by jv110** [comment]
@minecraftmuse3 I think he meant "Do you want to help us?"

**Comment by minecraftmuse3** [comment]
@RedstoneGunMade What function name?

**Comment by minecraftmuse3** [comment]
@jv110 Yes I do

**Comment by jv110** [comment]
setBlockBounds(0.0F, 0.0F, 0.0F, 1.0F, 0.625F, 1.0F);
works the same way as
tess->setRenderBounds(0.0F, 0.0F, 0.0F, 1.0F, 0.625F, 1.0F);

**Comment by RedstoneGunMade** [comment]
@minecraftmuse3 please say your twitter pls
PS: I'm Spanish, sorry for weird words ;(

**Comment by minecraftmuse3** [comment]
Where can I find it? In the "BlockAnvil.java"?

**Comment by RedstoneGunMade** [comment]
@jv110 it works? Cauldron had it and doesn't compile

**Comment by minecraftmuse3** [comment]
@RedstoneGunMade My Twitter is @DamienMiller11

**Comment by jv110** [comment]
@minecraftmuse3 yeah

**Comment by RedstoneGunMade** [comment]
@minecraftmuse3 pls follow me for add you into group (I'm @RedstoneGunMade)

**Comment by minecraftmuse3** [comment]
@jv110 Let me take a look

**Comment by minecraftmuse3** [comment]
This part?

Override public void setBlockBoundsBasedOnState(IBlockAccess par1IBlockAccess, int par2, int par3, int par4)
	{
		int var5 = par1IBlockAccess.getBlockMetadata(par2, par3, par4) & 3;
		if(var5 != 3 && var5 != 1)
		{
			setBlockBounds(0.125F, 0.0F, 0.0F, 0.875F, 1.0F, 1.0F);
		} else
		{
			setBlockBounds(0.0F, 0.0F, 0.125F, 1.0F, 1.0F, 0.875F);
		}
	}

**Comment by jv110** [comment]
No, that's the one to make it connect... I think it's not in that file. Let me search.

**Comment by CrazyWolf23** [comment]
Im working on the anvil

**Comment by jv110** [comment]
*lel*
